# Generated by Django 3.2.7 on 2021-09-24 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mpesa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayBillPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TransactionType', models.CharField(max_length=30)),
                ('TransID', models.CharField(max_length=255)),
                ('TransAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('BusinessShortCode', models.CharField(max_length=50)),
                ('BillRefNumber', models.CharField(max_length=50)),
                ('InvoiceNumber', models.CharField(max_length=50)),
                ('OrgAccountBalance', models.CharField(max_length=50)),
                ('ThirdPartyTransID', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
                ('firstName', models.CharField(max_length=50)),
                ('middleName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
            ],
        ),
    ]
