# Generated by Django 3.2.7 on 2021-09-24 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mpesa', '0002_paybillpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paybillpayment',
            name='TransAmount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
