# Generated by Django 3.2.7 on 2021-09-27 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mpesa', '0003_alter_paybillpayment_transamount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paybillpayment',
            old_name='firstName',
            new_name='FirstName',
        ),
        migrations.RenameField(
            model_name='paybillpayment',
            old_name='lastName',
            new_name='LastName',
        ),
        migrations.RenameField(
            model_name='paybillpayment',
            old_name='middleName',
            new_name='MSISDN',
        ),
        migrations.RenameField(
            model_name='paybillpayment',
            old_name='phone_number',
            new_name='MiddleName',
        ),
    ]
